// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCuODjJTkMBxWF2bq44qq1cUOkg1iHdp40',
    appId: '1:855852171121:web:3189c6937fd8d4094740d0',
    messagingSenderId: '855852171121',
    projectId: 'ej-mymaktaba',
    authDomain: 'ej-mymaktaba.firebaseapp.com',
    storageBucket: 'ej-mymaktaba.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyANEWSBGPmQfYdtu_A7HeW9wNDDEX-MWOA',
    appId: '1:855852171121:android:34a4fb34d05b6aa04740d0',
    messagingSenderId: '855852171121',
    projectId: 'ej-mymaktaba',
    storageBucket: 'ej-mymaktaba.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAHYiCWYILpLq-ZkNPWo7-XEQD9zUAIkZs',
    appId: '1:855852171121:ios:7be568844ccf0cf34740d0',
    messagingSenderId: '855852171121',
    projectId: 'ej-mymaktaba',
    storageBucket: 'ej-mymaktaba.firebasestorage.app',
    iosClientId:
        '855852171121-r8jv798t0njq1fu7hne7alsk3r8ggcth.apps.googleusercontent.com',
    iosBundleId: 'me.josephat.mymaktaba',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAHYiCWYILpLq-ZkNPWo7-XEQD9zUAIkZs',
    appId: '1:855852171121:ios:7fc247f3d15e4b8e4740d0',
    messagingSenderId: '855852171121',
    projectId: 'ej-mymaktaba',
    storageBucket: 'ej-mymaktaba.firebasestorage.app',
    iosClientId:
        '855852171121-4qpjol6gb5iurvqplbrht63i0174hqea.apps.googleusercontent.com',
    iosBundleId: 'me.josephat.mymaktaba',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCuODjJTkMBxWF2bq44qq1cUOkg1iHdp40',
    appId: '1:855852171121:web:5b75b18d701c0f774740d0',
    messagingSenderId: '855852171121',
    projectId: 'ej-mymaktaba',
    authDomain: 'ej-mymaktaba.firebaseapp.com',
    storageBucket: 'ej-mymaktaba.firebasestorage.app',
  );
}
